name: Deploy Git.WTF

on: [push]

jobs:
  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Deploy
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
        DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
      run: |
        eval "$(ssh-agent -s)"
        ssh-add - <<< "${DEPLOY_KEY}"
        mkdir ~/.ssh
        echo -e "HostName *\n\tStrictHostKeyChecking no" >> ~/.ssh/config
        ssh ${DEPLOY_USER}@${DEPLOY_HOST} 'cd ~/git.wtf && pwd'

