name: Deploy Git.WTF

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy To Production
    runs-on: ubuntu-18.04
    env:
      DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
      DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
      DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
    steps:
    - name: Notify slack that build has started
      if: success()
      id: slack # IMPORTANT: reference this step ID value in future Slack steps
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        channel: gitwtf
        status: STARTED
        color: warning
    - name: executing remote ssh commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        script: |
          cd ${{ secrets.DEPLOY_PATH }}
          pwd
          git pull deploy master
          # Let's tie any loose end's if there are any..
          composer install -q --no-ansi --no-interaction --no-suggest --no-progress --prefer-dist --optimize-autoloader --no-dev
          # If everything worked out correctly then clear any previous caches and rebuild new ones
          php artisan cache:clear
          php artisan config:cache
          php artisan route:cache
          php artisan responsecache:clear
          php artisan algolia:index
          # Finally, compile any assets that might have been updated
          yarn install
          yarn run production
          # We do need sitemap for SEO..
          php artisan sitemap:generate
    - name: Notify slack that build is success
      if: success()
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        message_id: ${{ steps.slack.outputs.message_id }}
        channel: gitwtf
        status: SUCCESS
        color: good
    - name: Notify slack that build has failed
      if: failure()
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        message_id: ${{ steps.slack.outputs.message_id }}
        channel: gitwtf
        status: FAILED
        color: danger

