name: Deploy Git.WTF

on: 
  push:
  pull_request:
    branches: 
      - master

jobs:
  deploy:
    name: deploy to production
    runs-on: ubuntu-18.04
    env:
      DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
      DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
      DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
    steps:
    - name: executing remote ssh commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        script: |
          cd /home/msingh/git.wtf
          pwd
          git pull origin master

